<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends \Doctrine\ORM\EntityRepository
{
    public function myFindAllByUser(User $user)
    {
        return $this->createQueryBuilder('m')
                    ->join('m.client', 'u')
                    ->where('u.id = :user')
                    ->orWhere('u.roles LIKE :roles')
                    ->setParameter('user', $user)
                    ->setParameter('roles', 'ROLE_ADMIN')
                    ->getQuery()
                    ->getResult()
            ;
    }
}
