<?php

namespace AppBundle\Repository;

use AppBundle\Entity\User;

/**
 * MissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MissionRepository extends \Doctrine\ORM\EntityRepository
{
    private function base()
    {
        return $this->createQueryBuilder('m')
                    ->join('m.client', 'u');
    }

    public function myFindAllByUser(User $user, $isAdmin)
    {
        $qb = $this->base();

        if ($isAdmin === false) {
            $qb->where('u.id = :user')
                ->setParameter('user', $user);
        }

        return $qb->getQuery()->getResult();
    }
}
